"""Work Object aggregate for workflow integration tracking."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from ds_agent.domain.entities._id_patterns import WORK_OBJECT_ID_PATTERN
from ds_agent.domain.entities.external_reference import ExternalReference
from ds_agent.domain.errors.work_object_errors import WorkObjectStateError


class RequestSource(StrEnum):
    """Where the request originated."""

    SLACK = "slack"
    EMAIL = "email"
    JIRA = "jira"
    CLI = "cli"
    TELEGRAM = "telegram"
    ELECTRON = "electron"
    API = "api"


class WorkObjectPhase(StrEnum):
    """Lifecycle phase for a work object."""

    INTAKE = "intake"
    EXECUTING = "executing"
    REVIEW = "review"
    DOCUMENTING = "documenting"
    FOLLOWUP = "followup"
    CLOSED = "closed"
    FAILED = "failed"


class FollowUpActionStatus(StrEnum):
    """Operational status for a follow-up action."""

    PENDING = "pending"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class RequestSection(BaseModel):
    """Who asked for what, and from which channel."""

    model_config = ConfigDict(validate_assignment=True)

    source: RequestSource
    requestor_id: str = Field(min_length=1)
    requestor_display: str = Field(min_length=1)
    original_text: str = Field(min_length=1)
    channel: str | None = None
    received_at: datetime
    external_ref: ExternalReference | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionSection(BaseModel):
    """Execution state tied back to TaskContract and runs."""

    model_config = ConfigDict(validate_assignment=True)

    task_contract_id: str = Field(min_length=1)
    run_ids: list[str] = Field(default_factory=list)
    current_phase: WorkObjectPhase = WorkObjectPhase.INTAKE
    started_at: datetime | None = None
    completed_at: datetime | None = None


class DocumentationSection(BaseModel):
    """Artifacts and external documents produced while executing."""

    model_config = ConfigDict(validate_assignment=True)

    delivery_pack_id: str | None = None
    references: list[ExternalReference] = Field(default_factory=list)


class FollowUpAction(BaseModel):
    """One downstream action generated by the workflow."""

    model_config = ConfigDict(validate_assignment=True)

    action_type: Literal["ticket", "calendar", "message", "dashboard_update"]
    description: str = Field(min_length=1)
    external_ref: ExternalReference
    policy_decision_id: str | None = None
    status: FollowUpActionStatus = FollowUpActionStatus.PENDING


class FollowUpSection(BaseModel):
    """Collection of downstream actions."""

    model_config = ConfigDict(validate_assignment=True)

    actions: list[FollowUpAction] = Field(default_factory=list)


class WorkObject(BaseModel):
    """Execution-tracking view for one task contract."""

    model_config = ConfigDict(validate_assignment=True)

    work_object_id: str = Field(pattern=WORK_OBJECT_ID_PATTERN)
    title: str = Field(min_length=1)
    request: RequestSection
    execution: ExecutionSection
    documentation: DocumentationSection = Field(default_factory=DocumentationSection)
    follow_up: FollowUpSection = Field(default_factory=FollowUpSection)
    created_at: datetime
    updated_at: datetime
    owner_agent: str = Field(min_length=1)
    tags: list[str] = Field(default_factory=list)
    parent_work_object_id: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def has_pending_follow_up_actions(self) -> bool:
        return any(
            action.status == FollowUpActionStatus.PENDING
            for action in self.follow_up.actions
        ) or any(
            item.get("status") == "pending"
            for item in self.metadata.get("pending_policy_actions", [])
            if isinstance(item, dict)
        )

    def register_run(self, run_id: str, *, when: datetime) -> None:
        if run_id and run_id not in self.execution.run_ids:
            self.execution.run_ids.append(run_id)
            self.updated_at = when

    def advance_to(self, to_phase: WorkObjectPhase, *, when: datetime) -> None:
        current = self.execution.current_phase
        if to_phase == current:
            self.updated_at = when
            return
        allowed = {
            WorkObjectPhase.INTAKE: {WorkObjectPhase.EXECUTING, WorkObjectPhase.FAILED},
            WorkObjectPhase.EXECUTING: {WorkObjectPhase.REVIEW, WorkObjectPhase.FAILED},
            WorkObjectPhase.REVIEW: {WorkObjectPhase.DOCUMENTING, WorkObjectPhase.FAILED},
            WorkObjectPhase.DOCUMENTING: {WorkObjectPhase.FOLLOWUP, WorkObjectPhase.FAILED},
            WorkObjectPhase.FOLLOWUP: {WorkObjectPhase.CLOSED, WorkObjectPhase.FAILED},
            WorkObjectPhase.CLOSED: set(),
            WorkObjectPhase.FAILED: set(),
        }
        if to_phase not in allowed[current]:
            raise WorkObjectStateError(
                f"Cannot transition work object from {current} to {to_phase}"
            )
        if to_phase == WorkObjectPhase.FOLLOWUP and not self.documentation.references:
            raise WorkObjectStateError(
                "Cannot transition work object to followup without at least one "
                "documentation reference"
            )
        if to_phase == WorkObjectPhase.CLOSED and self.has_pending_follow_up_actions:
            raise WorkObjectStateError(
                "Cannot close work object while follow-up actions are pending"
            )
        if to_phase == WorkObjectPhase.EXECUTING and self.execution.started_at is None:
            self.execution.started_at = when
        if to_phase in {WorkObjectPhase.CLOSED, WorkObjectPhase.FAILED}:
            self.execution.completed_at = when
        self.execution.current_phase = to_phase
        self.updated_at = when

    def attach_reference(
        self,
        reference: ExternalReference,
        *,
        location: Literal["request", "documentation", "follow_up"],
        when: datetime,
        action_type: Literal["ticket", "calendar", "message", "dashboard_update"] = "message",
        description: str | None = None,
        policy_decision_id: str | None = None,
    ) -> None:
        if location == "request":
            self.request.external_ref = reference
        elif location == "documentation":
            if reference.identity not in {item.identity for item in self.documentation.references}:
                self.documentation.references.append(reference)
        else:
            existing = next(
                (
                    action
                    for action in self.follow_up.actions
                    if action.external_ref.identity == reference.identity
                ),
                None,
            )
            if existing is None:
                status_value = reference.metadata.get("status")
                try:
                    status = (
                        FollowUpActionStatus(str(status_value))
                        if status_value is not None
                        else FollowUpActionStatus.PENDING
                    )
                except ValueError:
                    status = FollowUpActionStatus.PENDING
                self.follow_up.actions.append(
                    FollowUpAction(
                        action_type=action_type,
                        description=description or reference.resource_type,
                        external_ref=reference,
                        policy_decision_id=policy_decision_id,
                        status=status,
                    )
                )
        self._clear_pending_policy_action(reference.idempotency_key)
        self.updated_at = when

    def queue_pending_policy_action(
        self,
        *,
        system: str,
        action: str,
        location: Literal["request", "documentation", "follow_up"],
        description: str,
        idempotency_key: str,
        policy_decision_id: str,
        reason: str,
        when: datetime,
    ) -> None:
        pending = [
            item
            for item in self.metadata.get("pending_policy_actions", [])
            if isinstance(item, dict) and item.get("idempotency_key") != idempotency_key
        ]
        pending.append(
            {
                "system": system,
                "action": action,
                "location": location,
                "description": description,
                "idempotency_key": idempotency_key,
                "policy_decision_id": policy_decision_id,
                "status": "pending",
                "reason": reason,
                "created_at": when.isoformat(),
            }
        )
        self.metadata["pending_policy_actions"] = pending
        self.updated_at = when

    def _clear_pending_policy_action(self, idempotency_key: str) -> None:
        pending = self.metadata.get("pending_policy_actions")
        if not isinstance(pending, list):
            return
        self.metadata["pending_policy_actions"] = [
            item
            for item in pending
            if not isinstance(item, dict) or item.get("idempotency_key") != idempotency_key
        ]
