"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArtifactsPage = ArtifactsPage;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_i18next_1 = require("react-i18next");
const filesStore_1 = require("../../renderer/stores/filesStore");
function ArtifactsPage() {
    const { t } = (0, react_i18next_1.useTranslation)('mobile');
    const fileGroups = (0, filesStore_1.useFilesStore)((state) => state.fileGroups);
    const plotGroups = (0, filesStore_1.useFilesStore)((state) => state.plotGroups);
    const flattenedFiles = fileGroups.flatMap((group) => group.entries).slice(0, 6);
    const flattenedPlots = plotGroups.flatMap((group) => group.entries).slice(0, 4);
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col gap-3 p-4", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-lg font-semibold text-ds-text", children: t('nav.artifacts') }), (0, jsx_runtime_1.jsx)("span", { className: "text-xs text-ds-muted", children: t('status.readOnly') }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-ds-muted", children: t('artifacts.description') }), (0, jsx_runtime_1.jsxs)("section", { className: "rounded-2xl border border-ds-border bg-ds-surface/70 p-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between gap-3", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-sm font-semibold text-ds-text", children: t('artifacts.files.title') }), (0, jsx_runtime_1.jsx)("p", { className: "mt-1 text-xs leading-5 text-ds-muted", children: t('artifacts.files.description') })] }), (0, jsx_runtime_1.jsx)("span", { className: "rounded-full bg-ds-surface px-2 py-1 text-[11px] text-ds-muted", children: flattenedFiles.length })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-4 space-y-3", children: flattenedFiles.length === 0 ? ((0, jsx_runtime_1.jsx)("div", { className: "rounded-xl border border-ds-border/70 bg-ds-bg/50 p-3 text-sm text-ds-muted", children: t('artifacts.files.empty') })) : (flattenedFiles.map((file) => ((0, jsx_runtime_1.jsxs)("article", { className: "rounded-xl border border-ds-border/70 bg-ds-bg/50 p-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-sm font-medium text-ds-text", children: file.name }), (0, jsx_runtime_1.jsx)("div", { className: "mt-1 break-all text-xs text-ds-muted", children: file.path })] }, file.path)))) })] }), (0, jsx_runtime_1.jsxs)("section", { className: "rounded-2xl border border-ds-border bg-ds-surface/70 p-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between gap-3", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-sm font-semibold text-ds-text", children: t('artifacts.plots.title') }), (0, jsx_runtime_1.jsx)("span", { className: "rounded-full bg-ds-surface px-2 py-1 text-[11px] text-ds-muted", children: flattenedPlots.length })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-4 space-y-3", children: flattenedPlots.length === 0 ? ((0, jsx_runtime_1.jsx)("div", { className: "rounded-xl border border-ds-border/70 bg-ds-bg/50 p-3 text-sm text-ds-muted", children: t('artifacts.plots.empty') })) : (flattenedPlots.map((plot) => ((0, jsx_runtime_1.jsxs)("article", { className: "rounded-xl border border-ds-border/70 bg-ds-bg/50 p-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-sm font-medium text-ds-text", children: plot.name }), (0, jsx_runtime_1.jsx)("div", { className: "mt-1 break-all text-xs text-ds-muted", children: plot.path })] }, plot.path)))) })] })] }));
}
